config/routes.rb
Rails.application.routes.draw do
  resources :coins
  resources :cryptos
  devise_for :people
  devise_for :users
  get '/about' => 'static_pages#about'
  get '/history' => 'static_pages#history'
  get '/lookup' => 'static_pages#lookup'
  post '/lookup' => 'static_pages#lookup'
  root to: "home#index"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
  def history
    @coins = Coin.all
    require 'net/http'
    require 'json'
    @url = 'https://api.coinmarketcap.com/v1/ticker/?limit=1000'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @lookup_coins = JSON.parse(@response)
    @profit_lost = 0
    @profit_summ = 0
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_history_empty.erb
<br>
    <h2 class="w-100 text-center"><%= t('history_h') %> </h2>
    <h3  class="w-100 text-center"> <%= t('history_p') %> </h3>
 
<div class="card card-profile ml-auto mr-auto" style="max-width: 500px">
 <div class="card-body ">
        <h3 class="card-category text-dark">
            1. <%= t('history_instr1') %>
        </h3>
    </div>
  <div class="card-header card-header-image">
       
            <%= image_tag("/img/1.jpg", class: " img") %>
      
    </div>
   
</div>
<br>
<br>

<div class="card card-profile ml-auto mr-auto" style="max-width: 500px">
<div class="card-body ">
        <h3 class="card-category text-dark">
            2. <%= t('history_instr2') %>
        </h3>
    </div>
  <div class="card-header card-header-image">
        
            <%= image_tag("/img/2.jpg", class: " img") %>
        
    </div>
    
</div>

app/views/static_pages/_home_have_coin.erb
<!-- If user login -->
<div class="row">
        <div class="col-md-12">
            <section class="jumbotron text-center">
                <div class="container">
             
                <h3 class="jumbotron-heading">
                    <%= t('descr_after_login_home') %>   
                </h3>
                    <%= link_to t('portfolio'), coins_path, class: "btn btn-info" %>
                    <%= link_to t('add_new_coin'), new_coin_path, class: "btn btn-success" %>
                </p>
                </div>
            </section>
        </div>
    </div>

app/views/static_pages/_home_have_not_coin.erb
<!-- If user login -->
<div class="row">

        <div class="col-md-12">
            <section class="jumbotron text-center">
                <div class="container">
             
                <h3 class="jumbotron-heading">
                    <%= t('portfolio_empty') %>   
                </h3>
               <p>
                    <%= link_to t('add_new_coin'), new_coin_path, class: "btn btn-success" %>
                </p>
                </div>
            </section>
        </div>
    </div>

app/views/static_pages/_if_history_not_empty.erb
 <h3 class="text-uppercase text-center mt-4"><%= t('history') %></h3>
    <div class="row pb-5">
      <div class="col-12">
        <div class="change__value">
          <span class="badge w-100 badge-success">
            <p class="m-3"><%= t('profit_lost') %> </p>
            <p id="historyProfLost" class="change__val m-3"></p>
          </span>
        </div>
      </div>
    </div>
    <div class="row">
      <% @coins.each do |coin| %>
        <!-- *** -->
        <!-- If the coin does not matter in the cost_per_sold field, then it is not sold. And you need to show it here  -->
        <!-- *** -->
        <% if coin.person_id == current_person.id && coin.cost_per_sold %>
          <% if coin.symbol %>
            <% coin.symbol = coin.symbol.upcase %>
              <% end %>
                <% for x in @lookup_coins %>
                  <% if coin.symbol == x["symbol"] %>
                    <div class="col-md-6 wrap__each__coin">
                      <div class="card card-nav-tabs">
                        <h3 class="card-header card-header-primary text-uppercase coin__name">
                          <%= x["name"] %>
                        </h3>
                        <div class="card-body">
                          
                          <!-- END row -->
                          <div class="row static2row mt-2 mb-2">
                            <div class="col-12">
                              <div class="change__value">
                                <span class="badge w-100">
                                  <p class="m-3"> <%= t('profit_lost') %> </p>
                                  <p class="change__val proit__lost m-3">
                                    <% profit_lost_coin = (coin.cost_per_sold * coin.amount_owned).to_i - (coin.cost_per * coin.amount_owned).to_i %>
                         <%= profit_lost_coin %>
                                  </p>
                                </span>
                              </div>
                            </div>
                          </div>
                          
                          <br>
                          <div class="footer text-center coin__item__wrap">
                            <%= link_to 'Destroy', coin, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-just-icon btn-fill btn-round animated fadeIn" %>
                         
                          </div>
                        </div>
                      </div>
                    </div>

                    <% end %>
                      <% end %>
                        <% end %>
                          <% end %>
                           
    </div> <!-- Close row tag -->

app/views/static_pages/_lookup.html.erb
<h1> Look up </h1>

<%= form_tag lookup_path, :method => 'POST' do %>
  <%= text_field_tag 'sym', nil, placeholder: 'Enter Crypto Symbol', size: 50 %>
  <%= submit_tag 'Lookup Stock Quote' %>
<% end %>

<% if @symbol %>
  <% for x in @lookup_coins %>
    <% if @symbol == x["symbol"] %>
      <%= x["name"] %>: <%= x["price_usd"] %>$ | Rank: <%= x["rank"] %><br> 
    <% end %>
  <% end %>
<% end %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/history.html.erb
<div class="card">
  <div class="card-body">
  <% @soldcount = 0 %>
    <% @coins.each do |coin| %>
      <% if coin.person_id == current_person.id %>
        <% if coin.cost_per_sold.blank? %>  
        <% else %>
            <% @soldcount += 1 %>
        <% end %>
      <% end %>
    <% end %> 
    <!-- Render content -->  
    <% if (@soldcount >= 1) %>
      <%= render 'static_pages/if_history_not_empty' %>
    <% else %>
      <%= render 'static_pages/history_empty' %>
    <% end %>
   
      <br>
  </div>
</div>
<!-- Close MainCart (Wrap) -->


<script>
  jQuery(document).ready(function ($) {


 // Paste info about portolio value
           var profitLost = 0;
        $('.proit__lost').each(function () {
          profitLost += parseFloat($(this).text());
        });
        console.log(">>>>>" + profitLost);
        $('#historyProfLost').text(profitLost.toFixed(2));

    $(".coin__item__wrap a.btn-info").html('<i class="material-icons">subject</i>');
    $(".coin__item__wrap a.btn-success").html('<i class="material-icons">mode_edit</i>');
    $(".coin__item__wrap a.btn-danger").html('<i class="material-icons">delete</i>');
    $("#cardAddNewCoin a").html('<i class="material-icons">add</i>');
    // Change color depends value
    $(".change__value .badge").each(function () {
      var value = $(this).find(".change__val");
      var value = value.text();
      if (value >= 0) {
        $(this).addClass('badge-success');
      } else {
        $(this).addClass('badge-danger');
        $(this).find(".material-icons").text('trending_down');
      }
    });
    // Change color Summary
    var value = $("#wrapPortfSumm #moneyPortfLost");
    var value = value.text();
    if (value >= 0) {
      $('#wrapPortfSumm').addClass('bg-success');
    } else {
      $('#wrapPortfSumm').addClass('bg-danger');
    }


  });
</script>

app/views/static_pages/lookup.html.erb
<h1> Look up </h1>

<%= form_tag lookup_path, :method => 'POST' do %>
  <%= text_field_tag 'sym', nil, placeholder: 'Enter Crypto Symbol', size: 50 %>
  <%= submit_tag 'Lookup Stock Quote' %>
<% end %>

<% if @symbol %>
  <% for x in @lookup_coins %>
    <% if @symbol == x["symbol"] %>
      <%= x["name"] %>: <%= x["price_usd"] %>$ | Rank: <%= x["rank"] %><br> 
    <% end %>
  <% end %>
<% end %>