config/routes.rb
Rails.application.routes.draw do
  resources :coins
  resources :cryptos
  devise_for :people
  devise_for :users
  get '/about' => 'static_pages#about'
  get '/history' => 'static_pages#history'
  get '/lookup' => 'static_pages#lookup'
  post '/lookup' => 'static_pages#lookup'
  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_coin, only: [:show, :edit, :update, :destroy]
  before_action :correct_person, only: [:show, :edit, :update, :destroy]
  def index
    @coins = Coin.all
    require 'net/http'
    require 'json'
    @url = 'https://api.coinmarketcap.com/v1/ticker/?limit=1000'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @lookup_coins = JSON.parse(@response)
    @profit_lost = 0
    @profit_summ = 0
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_coin
    @coin = Coin.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def coin_params
    params.require(:coin).permit(:symbol, :person_id, :cost_per, :amount_owned)
  end
  def correct_person
    @correct = current_person.coins.find_by(id: params[:id])
    redirect_to coins_path, notice: "Пользователи не могут просматривать монеты других участников" if @correct.nil?
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_flash.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/home/_lookup.html.erb
<h1> Look up </h1>

<%= form_tag lookup_path, :method => 'POST' do %>
  <%= text_field_tag 'sym', nil, placeholder: 'Enter Crypto Symbol', size: 50 %>
  <%= submit_tag 'Lookup Stock Quote' %>
<% end %>

<% if @symbol %>
  <% for x in @lookup_coins %>
    <% if @symbol == x["symbol"] %>
      <%= x["name"] %>: <%= x["price_usd"] %>$ | Rank: <%= x["rank"] %><br> 
    <% end %>
  <% end %>
<% end %>

app/views/home/_navbar.html.erb
<% if !person_signed_in? %>
   <nav class="navbar navbar-expand-lg bg-primary">
                    <div class="container">
                        <div class="navbar-translate">
                            <a class="navbar-brand" href="/">BITCOINBTN.ru</a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                                <span class="navbar-toggler-icon"></span>
                                <span class="navbar-toggler-icon"></span>
                            </button>
                        </div>

                        <div class="collapse navbar-collapse">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item">
                                    <%= link_to t('sign_up'), new_person_registration_path, class: 'nav-link nav__sign-up' %>
                                </li>
                                <li class="nav-item">
                                    <%= link_to t('login'), new_person_session_path, class: "nav-link nav__login" %>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <script>
    jQuery(document).ready(function ($) {
        $("a.nav__sign-up").prepend('<i class="material-icons">person_add</i> ');
        $("a.nav__login").prepend('<i class="material-icons">person</i> ');
    });
</script>
<% else %>
            <nav class="navbar navbar-expand-lg bg-primary">
                    <div class="container">
                        <div class="navbar-translate">
                           <a class="navbar-brand" href="/">BITCOINBTN.ru</a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                                <span class="navbar-toggler-icon"></span>
                                <span class="navbar-toggler-icon"></span>
                            </button>
                        </div>

                        <div class="collapse navbar-collapse">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item">
                                    <%= link_to t('portfolio'), coins_path, class: 'nav-link nav__portfolio' %>
                                </li>
                                <li class="nav-item">
                                   <%= link_to  t('history'), history_path, class: 'nav-link nav__history' %>
                                </li>
                                <li class="nav-item">
                                   <%= link_to t('add_new_coin'), new_coin_path, class: 'nav-link nav__add-coin' %>
                                </li>
                                <li class="nav-item">
                                   <%= link_to t('setting_account'), edit_person_registration_path, class: 'nav-link nav__setting-account' %>
                                </li>
                                <li class="nav-item">
                                  <%= link_to t('logout'), destroy_person_session_path, method: :delete, class: 'nav-link nav__logout' %>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <script>
    jQuery(document).ready(function ($) {
        $("a.nav__portfolio").prepend('<i class="material-icons">work</i> ');
        $("a.nav__history").prepend('<i class="material-icons">history</i> ');
        $("a.nav__add-coin").prepend('<i class="material-icons">add_circle_outline</i> ');
        $("a.nav__setting-account").prepend('<i class="material-icons">settings</i> ');
        $("a.nav__logout").prepend('<i class="material-icons">exit_to_app</i> ');
    });
</script>
<% end %>






app/views/home/index.html.erb
<% if !person_signed_in? %>

                            

<table class="table__for__center" >
  <tbody>
    <tr>
      <td class="align-middle">
        <div class="text-center">
            <h3 class="jumbotron-heading"><%= t('problem1') %>. <%= t('problem2') %></h3>
                                <div class="col-12 text-center">
                                    <%= t('free') %>
                                </div>
                                <p>
                                    <%= link_to t('sign_up'), new_person_registration_path, class: 'btn btn-primary' %>
                                    <%= link_to t('login'), new_person_session_path, class: "btn btn-info" %>
                                </p>
        </div>
      </td>
    </tr>
  </tbody>
</table>
    
<% else %>

    <!-- Render content   -->  
    <% if 0 < (Coin.where(person_id: current_person.id).count) %>
    <!-- If User have coin --> 
      <%= render 'static_pages/home_have_coin' %>
    <% else %>
    <!-- If User did't coin --> 

      <%= render 'static_pages/home_have_not_coin' %>
    <% end %>
<% end %>