config/routes.rb
Rails.application.routes.draw do
  resources :coins
  resources :cryptos
  devise_for :people
  devise_for :users
  get '/about' => 'static_pages#about'
  get '/history' => 'static_pages#history'
  get '/lookup' => 'static_pages#lookup'
  post '/lookup' => 'static_pages#lookup'
  root to: "home#index"
end

app/models/crypto.rb
class Crypto < ApplicationRecord
    belongs_to :person
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_person!

  # GET /cryptos
  # GET /cryptos.json
  def index
    @cryptos = Crypto.all
  end

  # GET /cryptos/1
  # GET /cryptos/1.json
  def show
  end

  # GET /cryptos/new
  def new
    @crypto = Crypto.new
  end

  # GET /cryptos/1/edit
  def edit
  end

  # POST /cryptos
  # POST /cryptos.json
  def create
    @crypto = Crypto.new(crypto_params)

    respond_to do |format|
      if @crypto.save
        format.html { redirect_to @crypto, notice: 'Crypto was successfully created.' }
        format.json { render :show, status: :created, location: @crypto }
      else
        format.html { render :new }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptos/1
  # PATCH/PUT /cryptos/1.json
  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        format.html { redirect_to @crypto, notice: 'Crypto was successfully updated.' }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptos/1
  # DELETE /cryptos/1.json
  def destroy
    @crypto.destroy
    respond_to do |format|
      format.html { redirect_to cryptos_url, notice: 'Crypto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto
      @crypto = Crypto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crypto_params
      params.require(:crypto).permit(:symbol, :user_id, :cost_per, :amount_owner)
    end
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/views/cryptos/_form.html.erb
<%= form_with(model: crypto, local: true) do |form| %>
  <% if crypto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crypto.errors.count, "error") %> prohibited this crypto from being saved:</h2>

      <ul>
      <% crypto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, value: current_person.id %>
  </div>

  <div class="field">
    <%= form.label :cost_per %>
    <%= form.text_field :cost_per %>
  </div>

  <div class="field">
    <%= form.label :amount_owner %>
    <%= form.text_field :amount_owner %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cryptos/edit.html.erb
<h1>Editing Crypto</h1>

<%= render 'form', crypto: @crypto %>

<%= link_to 'Show', @crypto %> |
<%= link_to 'Back', cryptos_path %>

app/views/cryptos/index.html.erb
<h1>Cryptos</h1>

<table>
  <thead>
    <tr>
      <th>Symbol</th>
      <th>User</th>
      <th>Cost per</th>
      <th>Amount owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<%= current_person.id %>
  <tbody>
    <% @cryptos.each do |crypto| %>
    <% if crypto.user_id == current_person.id  %>
   
      <tr>
        <td><%= crypto.symbol %></td>
        <td><%= crypto.user_id %></td>
        <td><%= crypto.cost_per %></td>
        <td><%= crypto.amount_owner %></td>
        <td><%= link_to 'Show', crypto %></td>
        <td><%= link_to 'Edit', edit_crypto_path(crypto) %></td>
        <td><%= link_to 'Destroy', crypto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crypto', new_crypto_path %>

app/views/cryptos/new.html.erb
<h1>New Crypto</h1>

<%= render 'form', crypto: @crypto %>

<%= link_to 'Back', cryptos_path %>

app/views/cryptos/show.html.erb
<p>
  <strong>Symbol:</strong>
  <%= @crypto.symbol %>
</p>

<p>
  <strong>User:</strong>
  <%= @crypto.user_id %>
</p>

<p>
  <strong>Cost per:</strong>
  <%= @crypto.cost_per %>
</p>

<p>
  <strong>Amount owner:</strong>
  <%= @crypto.amount_owner %>
</p>

<%= link_to 'Edit', edit_crypto_path(@crypto) %> |
<%= link_to 'Back', cryptos_path %>