config/routes.rb
Rails.application.routes.draw do
  resources :coins
  resources :cryptos
  devise_for :people
  devise_for :users
  get '/about' => 'static_pages#about'
  get '/history' => 'static_pages#history'
  get '/lookup' => 'static_pages#lookup'
  post '/lookup' => 'static_pages#lookup'
  root to: "home#index"
end

app/models/coin.rb
class Coin < ApplicationRecord
    belongs_to :person
    before_validation :make_only_symbol_for_coin
  private
    def make_only_symbol_for_coin
      self.symbol = symbol.split.first
    end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: [:show, :edit, :update, :destroy]
  before_action :correct_person, only: [:show, :edit, :update, :destroy]
 
  # GET /coins
  # GET /coins.json
  def index
    @coins = Coin.all
    require 'net/http'
    require 'json'
    @url = 'https://api.coinmarketcap.com/v1/ticker/?limit=1000'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @lookup_coins = JSON.parse(@response)
    @profit_lost = 0
    @profit_summ = 0
  end

  # GET /coins/1
  # GET /coins/1.json
  def show
    @coins = Coin.all
    require 'net/http'
    require 'json'
    @url = 'https://api.coinmarketcap.com/v1/ticker/?limit=1000'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @show_coins = JSON.parse(@response)
   
  end

  # GET /coins/new
  def new
    @coin = Coin.new
    @coins = Coin.all
    require 'net/http'
    require 'json'
    @url = 'https://api.coinmarketcap.com/v1/ticker/?limit=1000'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @show_coins_new = JSON.parse(@response)
   
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins
  # POST /coins.json
  def create
    @coin = Coin.new(coin_params)
   
    respond_to do |format|
      if @coin.save
        format.html { redirect_to coins_path, notice: 'Coin was successfully created.' }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1
  # PATCH/PUT /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coins_path, notice: 'Coin was successfully updated.' }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1
  # DELETE /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: 'Coin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coin_params
      params.require(:coin).permit(:symbol, :person_id, :cost_per, :amount_owned, :cost_per_sold, :is_it_sold)
    end
    def correct_person
      @correct = current_person.coins.find_by(id: params[:id])
      redirect_to coins_path, notice: "Users can not view coins of other participants" if @correct.nil?
    end

    

end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/views/coins/_form.html.erb
<div class="row">
  <div class="col-md-3">
  </div>
<div class="col-md-6 text-center">
<br>
  <div class="card card-signup p-5">
    <%= form_with(model: coin, local: true, :html => {:class => 'form-signin'}) do |form| %>
        <% if coin.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>
          <ul>
          <% coin.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>   
      <div class="form-signin">
        <%= image_tag("/img/bitcoin.svg", class: "mb-4", height: '72', width: '72') %>
          <h2 id="formTextHeader" class="h3 mb-4 mt-0 font-weight-normal text-uppercase">Add coin </h2>
      </div>
      <div id="formCoinName" class="form-label-group mb-3 text-left">
        <label for="exampleInputEmail1 text-dark" >Enter the name of the currency</label>
         <%= form.text_field :symbol, placeholder: "Start type name of currency", :required => 'required', :class => 'form-control' %>
      </div>
    
      <div class="form-label-group d-none">
       
       <%= form.number_field :person_id, value: current_person.id, type: "hidden" %>
      </div>
      
      <div class="form-label-group mb-3 text-left">
       <label for="exampleInputEmail1 text-dark" >The cost of one coin at the time of purchase</label>
       <%= form.text_field :cost_per, placeholder: "Price per coin", :required => 'required', :class => 'form-control' %>
      </div>
      <div class="form-label-group mb-3 text-left">
         <label for="exampleInputEmail1 text-dark" >Amount owned</label>
       <%= form.text_field :amount_owned, placeholder: "Amount owned", :required => 'required', :class => 'form-control' %>
      </div>
       <div class="form-label-group mb-3 text-left">
        <label for="exampleInputEmail1 text-dark" >Coin Was it sold?</label><br>
         <label for="exampleInputEmail1 text-dark" >Please, add Cost Per Sold: </label>
        <%= form.text_field :cost_per_sold, placeholder: "The value of the currency at the time of sale", :class => 'form-control' %>
      </div>
      <br>
      <!-- <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button> -->
      <%= form.submit "submit", :class => 'btn btn-lg btn-primary btn-block form__button' %>
      </form>
</div>
 

    </div>
    <div class="col-md-3">
    </div>
     </div>
<% end %>

app/views/coins/_form_add_new_coin.erb
<div class="row">
  <div class="col-md-3">
  </div>
<div class="col-md-6 text-center">
<br>
  <div class="card card-signup p-5">
    <%= form_with(model: coin, local: true, :html => {:class => 'form-signin'}) do |form| %>
        <% if coin.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>
          <ul>
          <% coin.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>   
      <div class="form-signin">
        <%= image_tag("/img/bitcoin.svg", class: "mb-4", height: '72', width: '72') %>
          <h2 id="formTextHeader" class="h3 mb-4 mt-0 font-weight-normal text-uppercase"><%= t('add_new_coin') %></h2>
      </div>
      <div id="formCoinName" class="form-label-group mb-3 text-left">
        <label for="exampleInputEmail1 text-dark" ><%= t('name_cur') %></label>
         <%= form.text_field :symbol, placeholder: t('name_cur_plh'), :required => 'required', :class => 'form-control' %>
      </div>
    
      <div class="form-label-group d-none">
       
       <%= form.number_field :person_id, value: current_person.id, type: "hidden" %>
      </div>
      
      <div class="form-label-group mb-3 text-left">
       <label for="exampleInputEmail1 text-dark" ><%= t('cur_price') %></label>
       <%= form.text_field :cost_per, placeholder: t('cur_price_plh'), :required => 'required', :class => 'form-control' %>
      </div>
      <div class="form-label-group mb-3 text-left">
         <label for="exampleInputEmail1 text-dark" ><%= t('amount') %></label>
       <%= form.text_field :amount_owned, placeholder: t('amount'), :required => 'required', :class => 'form-control' %>
      </div>
      <br>
      <!-- <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button> -->
      <%= form.submit t('add_new_coin'), :class => 'btn btn-lg btn-primary btn-block form__button' %>
      </form>
</div>
 

    </div>
    <div class="col-md-3">
    </div>
     </div>
<% end %>

app/views/coins/edit.html.erb
<div id="wrapEditForm">
    <%= render 'form', coin: @coin %>
    <br>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center"> 
    <li class="page-item"><%= link_to 'Back', coins_path, class:'page-link' %></li> 
    <li class="page-item"><%= link_to 'Show detail', @coin, class:'page-link' %></li>
  </ul>
</nav>
    <script>
jQuery(document).ready(function($) {

var inputCoinName = $("#formCoinName input").val();
console.log('inputCoinName' + inputCoinName);
$( "#wrapEditForm #formTextHeader" ).text( "Edit: " + inputCoinName );

});
</script>
</div>

app/views/coins/index.html.erb
<div class="card">
  <div class="card-body">
    <h3 class="text-uppercase text-center mt-4"><%= t('portfolio') %></h3>
    <div class="row">
      <div class="col-md-6 pb-5">
        <div class="card p-3">
          <p> <%= t('individual_cost') %>
          </p>
          <canvas id="myChart" width="100%" height="100%"></canvas>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card p-3">
          <div class="rounded bg-info m-3 p-2">
            <div class="card-body">
              <h5 class="text-uppercase font-weight-bold text-white mt-3 mb-3">
                <%= t('money_amount') %>
                <br>
                <span class="portfSummText"> $ </span>
                <span class="portfSummText" id="moneyPortfAmount"></span>
              </h5>
            </div>
          </div>
          <div id='wrapPortfSumm' class="rounded m-3 p-2">
            <div class="card-body">
              <h5 class="text-uppercase font-weight-bold text-white mt-3 mb-3">
                <%= t('profit_lost') %>
                <br>
                <span class="portfSummText" id="moneyPortfLost"></span>
                <span class="portfSummText">$</span>
              </h5>
            </div>
          </div>
        </div>
        <!-- close card p-3 -->
      </div>
      <!-- close col-md-6 -->
    </div>
    <!-- close col-md-6 -->
    <script>
      jQuery(document).ready(function ($) {
        var profitLost = 0;
        var curientVal = 0;
        $('.proit__lost').each(function () {
          profitLost += parseFloat($(this).text());
        });
        $('.curientValue').each(function () {
          curientVal += parseFloat($(this).text());
        });
        $('#moneyPortfAmount').text(curientVal.toFixed(2));
        $('#moneyPortfLost').text(profitLost.toFixed(2));
      });
    </script>

    <div class="row">
      <div class="col-12 mt-4 mb-1">
        <h3 class="text-uppercase text-center"><%= t('portfolio_detail') %></h3>
      </div>
    </div>
    <div class="row">
      <% @coins.each do |coin| %>
        <!-- *** -->
        <!-- If the coin does not matter in the cost_per_sold field, then it is not sold. And you need to show it here  -->
        <!-- *** -->
        <% if coin.person_id == current_person.id && coin.cost_per_sold.blank? %>
          <% if coin.symbol %>
            <% coin.symbol = coin.symbol.upcase %>
              <% end %>
                <% for x in @lookup_coins %>
                  <% if coin.symbol == x["symbol"] %>
                    <div class="col-md-6 wrap__each__coin">
                      <div class="card card-nav-tabs">
                        <h3 class="card-header card-header-primary text-uppercase coin__name">
                          <%= x["name"] %> =
                            <%= number_with_precision(x["price_usd"].to_d, precision: 2) %>$
                        </h3>
                        <div class="card-body">
                          <div class="row">
                            <div class="col-12 col-md-4">
                              <div class="change__value">
                                <span class="badge badge-success w-100 mb-3 mb-md-0">
                                  <p> <%= t('change') %> 7<%= t('d') %> </p>
                                  <p class="change__val">
                                    <%=  x["percent_change_7d"] %>
                                  </p>
                                  <i class="material-icons">trending_up</i>
                                </span>
                              </div>
                            </div>
                            <div class="col-12 col-md-4">
                              <div class="change__value">
                                <span class="badge badge-success w-100 mb-3 mb-md-0">
                                  <p> <%= t('change') %> 24<%= t('hs') %> </p>
                                  <p class="change__val">
                                    <%=  x["percent_change_24h"] %>
                                  </p>
                                  <i class="material-icons">trending_up</i>
                                </span>
                              </div>
                            </div>
                            <div class="col-12 col-md-4">
                              <div class="change__value">
                                <span class="badge badge-success w-100 mb-3 mb-md-0">
                                  <p> <%= t('change') %> 1<%= t('h') %> </p>
                                  <p class="change__val">
                                    <%=  x["percent_change_1h"]  %>
                                  </p>
                                  <i class="material-icons">trending_up</i>
                                </span>
                              </div>
                            </div>
                          </div>
                          <!-- END row -->
                          <div class="row static2row mt-2 mb-2">
                            <div class="col-12">
                              <div class="change__value">
                                <span class="badge w-100">
                                  <p class="m-3"> <%= t('profit_lost') %> </p>
                                  <p class="change__val proit__lost m-3">
                                    <% curval = (x["price_usd"].to_d * coin.amount_owned) - (coin.cost_per * coin.amount_owned) %>
                                      <%= number_with_precision(curval.to_d, precision: 2) %>
                                  </p>
                                </span>
                              </div>
                            </div>
                          </div>
                          <!-- END row -->
                          <div class="text-white bg-info p-2 mt-2 curr__value__coin">
                            <h5 class="text-white text-uppercase text-center font-weight-bold m-0 align-middle pt-3 pb-3"> <%= t('money_amount') %>: $
                              <span class="curientValue">
                                <%= number_with_precision(x["price_usd"].to_d * coin.amount_owned, precision: 2) %>
                              </span>
                            </h5>
                          </div>
                          <br>
                          <div class="footer text-center coin__item__wrap">
                            <%= link_to 'Show', coin, class: "btn btn-info btn-just-icon btn-fill btn-round animated fadeIn" %>
                              <%= link_to 'Edit', edit_coin_path(coin), class: "btn btn-success btn-just-icon btn-fill btn-round btn-wd animated fadeIn" %>
                                <%= link_to 'Destroy', coin, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-just-icon btn-fill btn-round animated fadeIn" %>
                          </div>
                        </div>
                      </div>
                    </div>

                    <% end %>
                      <% end %>
                        <% end %>
                          <% end %>
                            <!-- Add new coin -->
                            <div class="col-md-6">
                              <div class="card card-nav-tabs">
                                <h3 class="card-header card-header-primary text-uppercase ">
                                  <%= t('add_new_coin') %>
                               
                                </h3>
                                <div class="card-body">
                                  <div class="row">
                                    <div class="col-12">
                                      <div id="cardAddNewCoin" class="p-4 text-center">
                                        <span class="">
                                          <%= link_to 'New Coin', new_coin_path, class: "btn btn-success btn-just-icon btn-fill btn-round btn-wd animated fadeIn" %>
                                        </span>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <!-- End Add new coin -->
    </div> <!-- Close row tag -->
  </div>
</div>
<!-- Close MainCart (Wrap) -->


<script>
  jQuery(document).ready(function ($) {
    $(".coin__item__wrap a.btn-info").html('<i class="material-icons">subject</i>');
    $(".coin__item__wrap a.btn-success").html('<i class="material-icons">mode_edit</i>');
    $(".coin__item__wrap a.btn-danger").html('<i class="material-icons">delete</i>');
    $("#cardAddNewCoin a").html('<i class="material-icons">add</i>');
    // Change color depends value
    $(".change__value .badge").each(function () {
      var value = $(this).find(".change__val");
      var value = value.text();
      if (value >= 0) {
        $(this).addClass('badge-success');
      } else {
        $(this).addClass('badge-danger');
        $(this).find(".material-icons").text('trending_down');
      }
    });
    // Change color Summary
    var value = $("#wrapPortfSumm #moneyPortfLost");
    var value = value.text();
    if (value >= 0) {
      $('#wrapPortfSumm').addClass('bg-success');
    } else {
      $('#wrapPortfSumm').addClass('bg-danger');
    }
  });
</script>
<script>
  jQuery(document).ready(function ($) {
    // Chart #1 Start
    var coinsNames = [];
    var coinsSummary = [];

    $(".wrap__each__coin").each(function () {
      // For Name
      var coinName = $(this).find(".coin__name");

      var coinName = coinName.text();
      coinsNames.push(coinName);
      // For value
      var coinSumm = $(this).find(".curr__value__coin .curientValue").text();
      coinsSummary.push(coinSumm);

    });




    var ctx = document.getElementById("myChart").getContext('2d');
    var myChart = new Chart(ctx, {
      type: 'pie',
      data: {
        labels: coinsNames,
        datasets: [{
          label: '# of Votes',
          data: coinsSummary,
          backgroundColor: [


            '#99B2DD',
            '#F9DEC9',
            'rgba(153, 102, 255, 1)',

            'rgba(54, 162, 235, 1)',
            'rgba(255, 99, 132, 1)',
            'rgba(255, 159, 64, 1)'
          ],
          borderColor: [

            '#99B2DD',

            '#F9DEC9',
            'rgba(153, 102, 255, 1)',

            'rgba(54, 162, 235, 1)',
            'rgba(255,99,132,1)',
            'rgba(255, 159, 64, 1)'
          ],
          borderWidth: 1
        }]
      },

    });
    // Chart #1 End

  });
</script>

app/views/coins/new.html.erb
<%= render 'form_add_new_coin', coin: @coin %>

<script>
  jQuery(document).ready(function($) { 
    var availableTags = [
      <% for x in @show_coins_new %> 
        '<%= x["symbol"] %> | <%= x["name"] %>',
      <% end %>
    ];
    $( "#coin_symbol" ).autocomplete({
      source: availableTags
    });
 });
</script>

app/views/coins/show.html.erb
<% for x in @show_coins %>
  <% if @coin.symbol.upcase == x["symbol"] %>
    <% coin_name = x["name"] %>
    <% rank = x["rank"] %>
    <% price_usd = x["price_usd"] %>
    <% price_btc = x["price_btc"] %>
  
    <% market_cap_usd = x["market_cap_usd"] %>
    <% available_supply = x["available_supply"] %>
    <% total_supply = x["total_supply"] %>
    <% max_supply = x["max_supply"] %>
    <% percent_change_1h = x["percent_change_1h"] %>
    <% percent_change_24h = x["percent_change_24h"] %>
    <% percent_change_7d = x["percent_change_7d"] %>
    <% else %>
  <% end %>
<% end %>





  
    



<div class="container">
  <div class="card">
    <div class="card-body">
      <h3 class="text-uppercase text-center mt-4">Detailed statistics</h3>
      <table data-toggle="table">
          <thead>
              <tr>
                  <th>Title</th>
                  <th>Value</th>
              </tr>
          </thead>
          <tbody>
          <tr>
                  <td>Coin name:</td>
                  <td><%=  coin_name  %></td>
              </tr>
          <tr>
                  <td>Rank:</td>
                  <td><%=  rank  %></td>
              </tr>
              <tr>
                  <td>Price usd:</td>
                  <td><%=  price_usd  %></td>
              </tr>
              <tr>
                  <td>Price btc:</td>
                  <td><%=  price_btc  %></td>
              </tr>
              
              <tr>
                  <td>Market cap usd:</td>
                  <td><%=  market_cap_usd  %></td>
              </tr>
              <tr>
                  <td>Available supply:</td>
                  <td><%=  available_supply  %></td>
              </tr>
              <tr>
                  <td>Total supply:</td>
                  <td> <%= total_supply %></td>
              </tr>
              <tr>
                  <td>Max supply:</td>
                <td>
                  <%= max_supply  %>
                </td>
              </tr>

              <tr>
                  <td>Percent change 1h:</td>
                <td>
                  <%= percent_change_1h  %>
                </td>
              </tr>
              <tr>
                  <td>Percent change 24h:</td>
                <td>
                  <%= percent_change_24h  %>
                </td>
              </tr>
              <tr>
                  <td>Percent change 7d:</td>
                <td>
                  <%= percent_change_7d  %>
                </td>
              </tr>
          </tbody>
      </table>
        <div class="pt-4 pb-2 text-right">
          <%= link_to 'Edit', edit_coin_path(@coin), class:"btn btn-info"%>
          <%= link_to 'Back', coins_path, class:"btn btn-info" %>
        </div>
    </div>
  </div>
</div>

app/views/coins/sold.html.erb
<div id="wrapEditForm">
    <%= render 'form_edit', coin: @coin %>
    <br>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center"> 
    <li class="page-item"><%= link_to 'Back', coins_path, class:'page-link' %></li> 
    <li class="page-item"><%= link_to 'Show detail', @coin, class:'page-link' %></li>
  </ul>
</nav>
    <script>
jQuery(document).ready(function($) {

var inputCoinName = $("#formCoinName input").val();
console.log('inputCoinName' + inputCoinName);
$( "#wrapEditForm #formTextHeader" ).text( "Edit: " + inputCoinName );

});
</script>
</div>